### ISSUE TITLE
Extra new lines

### ISSUE THREAD

**Issue by ritz078** [brikou/CSS-in-JS-generator#2]
I am seeing that there are a lot of newlines in injectGlobal

<img width="449" alt="screen shot 2017-10-03 at 3 44 58 am" src="https://user-images.githubusercontent.com/5389035/31101914-6c28588a-a7ed-11e7-9950-f5048bb03c37.png">

**Comment by brikou** [comment]
In some generated files, formatting is wrong. I've open a related issue with prettier see https://github.com/prettier/prettier/issues/2883. I guess it should be solved soon. To bypass this problem, I added some "space" to avoid this https://github.com/brikou/CSS-in-JS-generator/blob/b3eb2ff39a569e738d6c6c4f2f103fcdfd342982/lib/convertScopedCssForEmotion.ts#L44-L45 but somewhere else it is too difficult to do this kind of trick.

For prettier to work with inject global, I first print `css` then replace if afterward with `injectGlobal` because injectGlobal is not a knwon keyword by prettier.

**Comment by ritz078** [comment]
I am not concerned about the tabs but a lot of empty lines present at the end.

**Comment by brikou** [comment]
Can you paste the CSS you are converting?

**Comment by ritz078** [comment]
It is the same as what you are using for your tests

```js
const x = `
*,
*::before,
*::after {
    box-sizing: inherit;
}
@-ms-viewport {
    width: device-width;
}
@media print {
    .badge {
        border: 1px solid #000;
    }
}
select.form-control:not([size]):not([multiple]) {
    height: calc(2.25rem + 2px);
}
.alert-dismissible .close {
    position: relative;
    top: -0.75rem;
    right: -1.25rem;
    padding: 0.75rem 1.25rem;
    color: inherit;
}
.alert-link {
    font-weight: bold;
}
.alert-primary {
    color: #004085;
    background-color: #cce5ff;
    border-color: #b8daff;
}
.alert-primary hr {
    border-top-color: #9fcdff;
}
.alert-primary .alert-link {
    color: #002752;
}
.badge {
    display: inline-block;
    padding: 0.25em 0.4em;
    font-size: 75%;
    font-weight: bold;
    line-height: 1;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: 0.25rem;
}
.badge-danger {
    color: #fff;
    background-color: #dc3545;
}
.badge-danger[href]:focus,
.badge-danger[href]:hover {
    color: #fff;
    text-decoration: none;
    background-color: #bd2130;
}
.badge:empty {
    display: none;
}
.blockquote-footer {
    display: block;
    font-size: 80%;
    color: #868e96;
}
.blockquote-footer::before {
    content: "\\\\2014 \\\\00A0";
}
.close {
    float: right;
    font-size: 1.5rem;
    font-weight: bold;
    line-height: 1;
    color: #000;
    text-shadow: 0 1px 0 #fff;
    opacity: .5;
}
.display-1 {
    font-size: 6rem;
    font-weight: 300;
    line-height: 1.1;
}
.display-2 {
    font-size: 5.5rem;
    font-weight: 300;
    line-height: 1.1;
}
.form-control::placeholder {
    color: #868e96;
    opacity: 1;
}
`
```

Once you move prettier to index.js, I can make a beta release and you can see the code.

**Comment by brikou** [comment]
In fact I use a trick to make prettier work with injectGlobal (as it does with css) template literals, see https://github.com/brikou/CSS-in-JS-generator/blob/master/index.ts#L29-L39
