### ISSUE TITLE
Move prettier to index.js

### ISSUE THREAD

**Issue by ritz078** [brikou/CSS-in-JS-generator#3]
I would like to use the package on the browser. But because of the usage of `prettier`, it breaks. I already use prettier after I get the output. Moving this to index.js will eventually separate the server side specific code.

**Comment by brikou** [comment]
I don't think it is because of prettier, I think what prevent browser usage is the use of npm's path. You can try to install https://github.com/jinder/path instead but havn't tried myself. Tests should break if it is not compliant.

**Comment by ritz078** [comment]
I can confirm that it is because of prettier. I have already made an initial demo by removing that part and it works as expected.

**Comment by brikou** [comment]
You can first try to comment this part (and also import) https://github.com/brikou/CSS-in-JS-generator/blob/b3eb2ff39a569e738d6c6c4f2f103fcdfd342982/lib/convertCssForEmotion.ts#L65-L68

If it works (in a ugly way) feel free to move this part to index.js, but some tests will broke

**Comment by brikou** [comment]
Another idea would be to just have this tool as a service, because I don't know if postcss can fully work on browser side.

**Comment by ritz078** [comment]
I have already tried by commenting it. Everything works fine. I am already using prettier on the client side. Also if you would like to know, you can apply prettier on the final output with `babylon` parser, it works fine.

Regarding tests. You can easily use prettier on the output before testing.

**Comment by brikou** [comment]
Done, you can check this PR https://github.com/brikou/CSS-in-JS-generator/commit/bbc64cabed8b46bdea74bdd7d8cbcef62fbac9eb
